# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SleepCycleCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SleepCycleCalculator(object):
    def setupUi(self, SleepCycleCalculator):
        SleepCycleCalculator.setObjectName("SleepCycleCalculator")
        SleepCycleCalculator.resize(400, 300)
        self.calcualteButton = QtWidgets.QPushButton(SleepCycleCalculator)
        self.calcualteButton.setGeometry(QtCore.QRect(80, 210, 93, 28))
        self.calcualteButton.setObjectName("calcualteButton")
        self.resetButton = QtWidgets.QPushButton(SleepCycleCalculator)
        self.resetButton.setGeometry(QtCore.QRect(230, 210, 93, 28))
        self.resetButton.setObjectName("resetButton")
        self.hourIn = QtWidgets.QLineEdit(SleepCycleCalculator)
        self.hourIn.setGeometry(QtCore.QRect(80, 110, 31, 22))
        self.hourIn.setObjectName("hourIn")
        self.minuteIn = QtWidgets.QLineEdit(SleepCycleCalculator)
        self.minuteIn.setGeometry(QtCore.QRect(130, 110, 31, 22))
        self.minuteIn.setObjectName("minuteIn")
        self.label = QtWidgets.QLabel(SleepCycleCalculator)
        self.label.setGeometry(QtCore.QRect(120, 110, 16, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(SleepCycleCalculator)
        self.textEdit.setGeometry(QtCore.QRect(220, 70, 104, 87))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(SleepCycleCalculator)
        self.resetButton.clicked.connect(self.hourIn.clear) # type: ignore
        self.resetButton.clicked.connect(self.minuteIn.clear) # type: ignore
        self.calcualteButton.clicked.connect(self.hourIn.copy) # type: ignore
        self.calcualteButton.clicked.connect(self.minuteIn.copy) # type: ignore
        self.resetButton.clicked.connect(self.textEdit.clear) # type: ignore
        self.textEdit.textChanged.connect(SleepCycleCalculator.accept) # type: ignore
        self.calcualteButton.clicked.connect(SleepCycleCalculator.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SleepCycleCalculator)

    def retranslateUi(self, SleepCycleCalculator):
        _translate = QtCore.QCoreApplication.translate
        SleepCycleCalculator.setWindowTitle(_translate("SleepCycleCalculator", "Dialog"))
        self.calcualteButton.setText(_translate("SleepCycleCalculator", "Calculate"))
        self.resetButton.setText(_translate("SleepCycleCalculator", "Reset"))
        self.label.setText(_translate("SleepCycleCalculator", ":"))
